dreamlife:
    resource: "@DreamlifeBundle/Resources/config/routing.yml"
    prefix:   /dreamlife

my_app:
    resource: "@MyAppBundle/Resources/config/routing.yml"
    prefix:   /app

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"