<?php

namespace MyAppBundle\Repository;

/**
 * NeudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeudRepository extends \Doctrine\ORM\EntityRepository
{
}
