<?php

namespace MyAppBundle\Repository;

/**
 * nodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nodeRepository extends \Doctrine\ORM\EntityRepository
{
}
