<?php

namespace DreamlifeBundle\Repository;

/**
 * nodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarninggRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindCount($i)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(sale.uid)');
        $qb->from('DreamlifeBundle:DreamlifePartnerSale','sale');
        $qb->where('sale.partnerUid = :name');
        $qb->setParameter('name', $i);
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
